version: '3'

services:
  server:
    build:
      dockerfile: ./server/Dockerfile
      context: .
      args:
        NODE_ENV: development
    ports:
      - 2000:2000
      - 9229:9229
    volumes:
      - ./server:/opt/accownt/server:delegated
      - ./server/package.json:/opt/accownt/server/package.json
      - ./server/package-lock.json:/opt/accownt/server/package-lock.json
      - unused1:/opt/accownt/server/node_modules
      - database:/opt/accownt/database
    command: npm run watch-start
    env_file: ./server/.env
  web:
    build:
      dockerfile: ./web/Dockerfile
      context: .
      args:
        NODE_ENV: development
    ports:
      - 2001:2001
    volumes:
      - ./web:/opt/accownt/web:delegated
      - ./web/package.json:/opt/accownt/web/package.json
      - ./web/package-lock.json:/opt/accownt/web/package-lock.json
      - unused2:/opt/accownt/web/node_modules
    command: npm run start
    env_file: ./web/.env

volumes:
  unused1:
  unused2:
  database: