version: '3'

services:
  server:
    build:
      dockerfile: ./server/Dockerfile
      context: .
      args:
        NODE_ENV: development
    ports:
      - 2000:2000
      - 9229:9229
      - 9230:9230
    volumes:
      - ./server:/opt/accownt/server:delegated
      - ./server/package.json:/opt/accownt/server/package.json
      - ./server/package-lock.json:/opt/accownt/server/package-lock.json
      - notused:/opt/accownt/server/node_modules
    command: npm run watch-start
    env_file: ./server/.env
volumes:
  notused: